package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/sylly-mika/authkit/migrations"
)

func appDir(t *testing.T, existing ...string) (dir, lock string) {
	t.Helper()
	dir = t.TempDir()
	for _, f := range existing {
		if err := os.WriteFile(filepath.Join(dir, f), []byte("SELECT 1;\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir, filepath.Join(t.TempDir(), "authkit.lock")
}

func names(paths []string) []string {
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = filepath.Base(p)
	}
	return out
}

func TestRunNumbersAfterTheAppsHighestMigration(t *testing.T) {
	dir, lock := appDir(t, "000007_saved_views.up.sql", "000007_saved_views.down.sql", "000008_rls_policies.up.sql", "000008_rls_policies.down.sql", "README.md", "atlas.sum")
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"})
	if err != nil {
		t.Fatal(err)
	}
	if want := []string{"000009_authkit_core.up.sql", "000009_authkit_core.down.sql"}; !slices.Equal(names(written), want) {
		t.Fatalf("wrote %v, want %v", names(written), want)
	}
}

func TestRunRendersThePrincipalsTableAndAHeader(t *testing.T) {
	dir, lock := appDir(t, "000001_init.up.sql")
	written, err := run(options{principals: "admins", out: dir, lock: lock, version: "v0.1.0"})
	if err != nil {
		t.Fatal(err)
	}
	up, _ := os.ReadFile(written[0])
	if s := string(up); strings.Contains(s, "{{") || !strings.Contains(s, "REFERENCES admins (id)") ||
		!strings.HasPrefix(s, "-- Generated by authkit-gen from github.com/sylly-mika/authkit v0.1.0, migration 0001_core.") {
		t.Fatalf("up = %s", s)
	}
}

func TestRunIsIdempotentThroughTheLock(t *testing.T) {
	dir, lock := appDir(t, "000003_x.up.sql")
	if _, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"}); err != nil {
		t.Fatal(err)
	}
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"})
	if err != nil || len(written) != 0 {
		t.Fatalf("second run wrote %v (%v), want nothing", written, err)
	}
	var l lockFile
	b, _ := os.ReadFile(lock)
	if err := json.Unmarshal(b, &l); err != nil || l.Library != "v0.1.0" || l.Principals != "users" ||
		len(l.Migrations) != 1 || l.Migrations[0].ID != 1 || l.Migrations[0].Name != "core" || l.Migrations[0].File != "000004_authkit_core" ||
		len(l.Migrations[0].SHA256) != 64 {
		t.Fatalf("lock = %+v (%v)", l, err)
	}
}

func TestRunRefusesAnotherPrincipalsTable(t *testing.T) {
	dir, lock := appDir(t)
	if _, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"}); err != nil {
		t.Fatal(err)
	}
	if _, err := run(options{principals: "admins", out: dir, lock: lock, version: "v0.1.0"}); err == nil {
		t.Fatal("a second principals table was accepted")
	}
}

func TestWriteNewNeverOverwrites(t *testing.T) {
	path := filepath.Join(t.TempDir(), "000009_authkit_core.up.sql")
	if err := os.WriteFile(path, []byte("applied"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writeNew(path, "replacement"); err == nil {
		t.Fatal("writeNew replaced an existing file")
	}
	if b, _ := os.ReadFile(path); string(b) != "applied" {
		t.Fatalf("the existing file now reads %q", b)
	}
}

func TestRunInAnEmptyDirectoryStartsAtOne(t *testing.T) {
	dir, lock := appDir(t)
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "(devel)"})
	if err != nil || names(written)[0] != "000001_authkit_core.up.sql" {
		t.Fatalf("wrote %v (%v)", written, err)
	}
}

func TestRunRefusesABadPrincipalsName(t *testing.T) {
	for _, bad := range []string{"users; DROP TABLE x", "Users", "user", "order", "group", "left", "auth_sessions", "pg_users"} {
		dir, lock := appDir(t)
		if _, err := run(options{principals: bad, out: dir, lock: lock, version: "v0.1.0"}); err == nil || !strings.HasPrefix(err.Error(), "authkit-gen: ") {
			t.Errorf("%q was rendered (%v), want an authkit-gen: refusal", bad, err)
		}
		if entries, _ := os.ReadDir(dir); len(entries) != 0 {
			t.Errorf("%q left %v in the migrations directory", bad, entries)
		}
		if _, err := os.Stat(lock); !os.IsNotExist(err) {
			t.Errorf("%q wrote the lock (%v)", bad, err)
		}
	}
}

func TestTheLockFileErrorsNameTheGenerator(t *testing.T) {
	missing := filepath.Join(t.TempDir(), "missing", "authkit.lock")
	if err := writeLock(missing, lockFile{}); err == nil || !strings.HasPrefix(err.Error(), "authkit-gen: ") {
		t.Errorf("writeLock into a missing directory = %v, want an authkit-gen: error", err)
	}
	if _, err := readLock(t.TempDir()); err == nil || !strings.HasPrefix(err.Error(), "authkit-gen: ") {
		t.Errorf("readLock of a directory = %v, want an authkit-gen: error", err)
	}
}

func TestRunRecordsTheVersionThatRanLast(t *testing.T) {
	dir, lock := appDir(t, "000008_rls_policies.up.sql")
	for _, v := range []string{"v0.1.0", "v0.2.0"} {
		if _, err := run(options{principals: "users", out: dir, lock: lock, version: v}); err != nil {
			t.Fatal(err)
		}
	}
	var l lockFile
	b, _ := os.ReadFile(lock)
	if err := json.Unmarshal(b, &l); err != nil || l.Library != "v0.2.0" {
		t.Fatalf("lock = %+v (%v), want library v0.2.0", l, err)
	}
}

func TestRunKeepsTheAppsDigitWidth(t *testing.T) {
	dir, lock := appDir(t, "0007_saved_views.up.sql", "0007_saved_views.down.sql")
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"})
	if want := []string{"0008_authkit_core.up.sql", "0008_authkit_core.down.sql"}; err != nil || !slices.Equal(names(written), want) {
		t.Fatalf("wrote %v (%v), want %v", names(written), err, want)
	}
}

func library(names ...string) []migrations.Migration {
	var out []migrations.Migration
	for i, n := range names {
		out = append(out, migrations.Migration{ID: i + 1, Name: n,
			Up:   fmt.Sprintf("CREATE TABLE auth_%s (p uuid REFERENCES {{principals}} (id));\n", n),
			Down: fmt.Sprintf("DROP TABLE auth_%s;\n", n)})
	}
	return out
}

func TestRunWritesOnlyWhatANewerLibraryAdded(t *testing.T) {
	dir, lock := appDir(t, "000008_rls_policies.up.sql")
	if _, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0", library: library("core")}); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "000010_app.up.sql"), []byte("SELECT 1;\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.2.0", library: library("core", "passkeys")})
	if want := []string{"000011_authkit_passkeys.up.sql", "000011_authkit_passkeys.down.sql"}; err != nil || !slices.Equal(names(written), want) {
		t.Fatalf("the upgrade wrote %v (%v), want %v", names(written), err, want)
	}
	if up, _ := os.ReadFile(written[0]); !strings.HasPrefix(string(up), "-- Generated by authkit-gen from github.com/sylly-mika/authkit v0.2.0, migration 0002_passkeys.") {
		t.Fatalf("up = %s", up)
	}
	var l lockFile
	b, _ := os.ReadFile(lock)
	if err := json.Unmarshal(b, &l); err != nil || len(l.Migrations) != 2 || l.Migrations[0].File != "000009_authkit_core" || l.Migrations[1].File != "000011_authkit_passkeys" {
		t.Fatalf("lock = %+v (%v)", l, err)
	}
}

func TestRunRefusesALockedMigrationThatChanged(t *testing.T) {
	dir, lock := appDir(t, "000008_rls_policies.up.sql")
	lib := library("core")
	if _, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0", library: lib}); err != nil {
		t.Fatal(err)
	}
	lib[0].Up += "CREATE INDEX idx_auth_core_p ON auth_core (p);\n"
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.1", library: lib})
	if err == nil || len(written) != 0 || !strings.Contains(err.Error(), "000009_authkit_core") {
		t.Fatalf("a changed 0001 wrote %v (%v), want a refusal naming 000009_authkit_core", names(written), err)
	}
}

func TestRunRefusesASecondCopyWithoutTheLock(t *testing.T) {
	dir, lock := appDir(t, "000008_rls_policies.up.sql", "000009_authkit_core.up.sql", "000009_authkit_core.down.sql")
	written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"})
	if err == nil || len(written) != 0 {
		t.Fatalf("000009_authkit_core present and no lock: wrote %v (%v), want a refusal", names(written), err)
	}
	if _, err := os.Stat(lock); !os.IsNotExist(err) {
		t.Fatalf("the refusal wrote the lock (%v)", err)
	}
}

func TestRunWritesNothingWhenTheLockCannotBeWritten(t *testing.T) {
	dir, _ := appDir(t, "000008_rls_policies.up.sql")
	lock := filepath.Join(t.TempDir(), "missing", "authkit.lock")
	if written, err := run(options{principals: "users", out: dir, lock: lock, version: "v0.1.0"}); err == nil || len(written) != 0 {
		t.Fatalf("wrote %v (%v), want a refusal before any write", names(written), err)
	}
	if entries, _ := os.ReadDir(dir); len(entries) != 1 {
		t.Fatalf("the migrations directory holds %v, want only the app's migration", entries)
	}
}
